### ISSUE TITLE
Furigana in all reviews

### ISSUE THREAD

**Issue by zoro11031** [SethClydesdale/genki-study-resources#13]
Apologies if this is already possible, but I couldn't find an option for it. I'm studying kanji using a tool separated from Grnki, so often i don't know the kanji for a chapter yet because the resource i use and Genki teach different kanji at different times. Is it possible to implement a furigana option for all reviews? Thanks!

**Comment by SethClydesdale** [comment]
Hello @zoro11031,

Thanks for bringing this to my attention.

Currently, furigana is only available in vocabulary and writing exercises, with some exceptions. Mostly due to limitations during the first development cycle. Towards the end of that cycle I had started working on an improved furigana display for other exercise types (that is currently accessible via the dictionary), which I hope to bring to the rest of the website eventually, though that probably wont be for some time.

For now, I recommend using the Rikaichan (Firefox) or Rikaikun (Chrome) extensions for exercises that don't have furigana, as they should help with identifying the pronunciation and meanings of kanji you don't know. If you're unable to use these extensions, you can try using the quick search in [the dictionary](https://sethclydesdale.github.io/genki-study-resources/lessons/appendix/dictionary/#dict-search-ja) as it should have 90% of the words used in Genki vol. I & II. For words unavailable, [Jisho](https://jisho.org/) is an excellent alternative.

I'll keep your issue open to help remind me to work on furigana implementations for the other exercise types.

Have a good day.

**Comment by SethClydesdale** [comment]
Hello again @zoro11031,

Since adding furigana to the current amount of exercises may prove to be a daunting task, for the time being I've added a "Quick Dictionary" to non-vocabulary exercises. This should help with quickly looking up words you've forgotten or simply do not know yet.

For exercises that support it, simply click the book icon in the bottom right-hand corner of the screen to open the quick dictionary. From there you can copy unknown kanji/words into the dictionary to search them. You can also type words to look up definitions.

![](https://i.imgur.com/AN1kwgv.png)

I hope this addition will be beneficial to you and everyone else.

Have a great weekend.

**Comment by SethClydesdale** [comment]
Hi again!

After taking time to consider the addition of furigana to exercises without it, I've decided to leave them as they are. Mostly because **1.** it would be quite the monumental task considering the amount of exercises that would need to be edited, and **2.** I don't want students to rely too heavily on furigana, since the first thing you should do in each lesson is memorize the vocabulary introduced, so that you have an easier time later on in the lesson.

I don't want to leave people completely without help however, which is why I've added the quick dictionary to help look up words and kanji, should you forget or not know a word. As one final addition, I've added an additional feature to the quick dictionary that'll allow you to quickly search words/kanji simply by selecting the texts. I hope that this'll make looking up unknown words easier.
![](https://i.imgur.com/3xfJc5M.png)
