### ISSUE TITLE
Lesson 8 Anki Cards

### ISSUE THREAD

**Issue by Paul-F-V** [SethClydesdale/genki-study-resources#144]
Hello again!  Rather than open a separate issue for each suggestion, I'll give you a collection of notes after each session (if I have one).

帰り is supposed to be a noun, so maybe it should say "return (noun)" or "[the] return?"

読書 says "reading books," which could be interpreted as "books for reading" when looking it up indicates that it means the act of reading.  I'm not sure how to best make this one clearer.  Maybe "[the act of] reading," or "reading (concept)?"

帰宅　and 帰国　both say something to the effect of going or returning home.  Maybe it would be easier to distinguish if "帰国" was read as "Return home [from abroad]?"

Instead of "reading materials," 読み物 is translated as "reading matter," which sounds awkward to me, an American.  Is this a Commonwealthism?

火事 just says "fire."  Since 火　is the neutral/basic version of the concept, would 火事　be better as "fire (disaster)?"

**Comment by SethClydesdale** [comment]
Hello @Paul-F-V!

帰り should be fine as it is. Verbs are typically labeled as "to XX", whereas nouns simply stand alone. An example:
遊ぶ　to play
遊び　play

Most verbs can be changed into nouns by using the stem (It was in a footnote, but I forget what they called it lol). It's basically like using の to qualify a sentence/verb as a noun. There is some minor differences though:
遊ぶのは楽しいです。　It's fun **_to_** play.
遊びは楽しいです。　Play/playing is fun.
They basically share the same meaning, however; the act of play(ing) is fun.

For 読書 changing it to reading (books) should be good.

I can see the issue with 帰国, so perhaps "returning to one's country" will suffice for this one.

In regards to 読み物 the provided translation is from the textbook (a large majority is, and considering the authors, this may explain some stilted terms). I believe the result is "reading matter" because of the combination of 読み (reading) and 物 (thing; object; matter). This is most likely how they came to their translation. I'll include "reading materials" as a secondary definition for this word.

火事 is a tricky one. Cross-referencing with both an electronic and my paper dictionary results with just "fire" or "conflagration." I think "fire (disaster)" is actually a good way to explain this one, since it helps differentiate from 火 itself which usually refers to fire such as a flame, the element.

I'll push these changes online later today.

Thanks again for the feedback.

**Comment by SethClydesdale** [comment]
Oops, almost forgot, but as of https://github.com/SethClydesdale/genki-study-resources/commit/dff1f244c311061dc79059f1d9296bd2cb54e8ad the anki decks/wordlists should be updated with these changes.

If anymore issues, do let me know.

**Comment by Paul-F-V** [comment]
Great!  Hey, is the backslash in "returning to one\'s country" a typo, or part of the code?

**Comment by SethClydesdale** [comment]
Ah, that's part of the code. Strings consist of two double or single quotes. If you use a double or single quote inside of those respective quotes, you have to escape it with a backslash, otherwise it breaks the string and basically kills the program lol.
