### ISSUE TITLE
Instant correctness feedback on non-multiple choice questions

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#211]
This feature is enabled for multiple-choice questions; I think it'd be great if it were implemented for example, for written exercises. 

Is it feasible? What do you think?

**Comment by SethClydesdale** [comment]
Hello!

I wouldn't say it's impossible, but would require quite a bit of reworking with how different the two exercise types work. Multiple choice automatically checks if the answer is correct when proceeding (even when this option is disabled), however, written exercises are only checked upon clicking the "check answers" button. I suppose one way to implement this could be to add a "check" button next to each problem, since auto-checking could be problematic. It'll be something to think about.

Thanks for the suggestion!
