### ISSUE TITLE
Kana / Kanji for the same word inconsistently accepted as correct or incorrect

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#233]
Hi,

Problem 2 in [this exercise](https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-17/grammar-3/) an example where the same word 嬉しい is accepted as wrong with the 嬉 and right without it.

Wrong:

![image](https://github.com/SethClydesdale/genki-study-resources/assets/2729079/b64bcee0-f5a7-415e-a4de-8418362f1ee3)

Right:

![image](https://github.com/SethClydesdale/genki-study-resources/assets/2729079/58540fb4-d271-43d9-924a-e0b1cf8835af)

Meanwhile Problem 3 is right with 嬉 or without it. Do you know if this Is intentional? I've noticed this in many other exercises as well, e.g. with 友達 and 友だち.

For example in https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-17/workbook-7/

![image](https://github.com/SethClydesdale/genki-study-resources/assets/2729079/a49c8699-e26b-47f5-8d83-4842efdbf6f5)

物 is not accepted in 3a for おいしい物, but _is_ accepted in 買い物.

**Comment by yangmillstheory** [comment]
Another example from https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-17/workbook-5/:

![image](https://github.com/SethClydesdale/genki-study-resources/assets/2729079/c07b3ebd-f414-47de-b4d1-56d9056f4846)

**Comment by yangmillstheory** [comment]
I have https://github.com/SethClydesdale/genki-study-resources/pull/235 to address the second comment. It's been a while since I've used GitHub :).

**Comment by SethClydesdale** [comment]
Hello!

Since the answers are static, there's a limited number of combinations. When originally going through, I only included kanji that was used in Genki, however, I added support for some commonly requested words such as 友達. The 嬉しい there should've been accepted, but it looks like I forgot to included one of the alternative kanji in that answer which bugged it out. I went ahead and corrected that along with adding 美味しい物 as an alternative too.

If you notice anything more like this, feel free to let me know!
