### ISSUE TITLE
第11課 - Reading Practice: 友だち募集

### ISSUE THREAD

**Issue by gcfreak** [SethClydesdale/genki-study-resources#3]
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-11/literacy-7/

In the "いっしょにバンドをやりませんか" section, there is a sentence that reads "ギターをひくのが好きで、**襲来**は歌手になりたいと思っています". 襲来 (しゅうらい) should be 将来 (しょうらい).
 
![capture](https://user-images.githubusercontent.com/47119443/52366751-5ae70680-29ff-11e9-9784-3350333102fd.PNG)

Thank you for putting together such an incredibly useful site! I appreciate the hard work.

**Comment by SethClydesdale** [comment]
Hi @gcfreak, thanks for the report ! I'll look into correcting this typo sometime tomorrow morning.

You're welcome, I'm glad it's of use to you ! At the moment I've put this project and my studies on hold due to personal health issues, but I hope to get back to working on it soon. Hopefully later this month if everything goes well. 🤞

**Comment by SethClydesdale** [comment]
https://github.com/SethClydesdale/genki-study-resources/commit/ff382a032ca0b76a043e073e80d6127e3be9cd13 should correct this typo.

Thanks again ! 👍
