### ISSUE TITLE
Answers not consistent in requiring 'の' and '-' in phone numbers

### ISSUE THREAD

**Issue by MartinFlores751** [SethClydesdale/genki-study-resources#33]
## Link it page in question:
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-1/workbook-3/

## Picture showing error:
![error](https://user-images.githubusercontent.com/22201770/71938431-fa16ff80-3174-11ea-9767-809b6d97faa8.png)

#### Expectation
Expected format should be:
from: ###-####
to:     〇〇〇の〇〇〇〇

#### Actual
All answers were missing の.

#### Expectation
Expected format should be:
from: 〇〇〇の〇〇〇〇
to:     ###-####

#### Actual
Answer with the area code missing hyphen separating the groups of numbers.

**Comment by MartinFlores751** [comment]
Correction, I made a mistake on the last question and I've also read the corrections wrong!

It seems that the error is actually with the mixture of hiragana and katakana in the same response.
I'm not sure if katakana support is intended, so I'll close this issue and won't open one on that.

Sorry for the mistake!

**Comment by SethClydesdale** [comment]
Hi @MartinFlores751,

You're correct that the issue is with the mix of hiragana and katakana. The answers in the textbook were given entirely in hiragana which is why katakana was not expected. I assume it's because katakana was taught more in lesson 2's reading and writing section or another reason, not sure haha. 

Anyway, I updated it in the background to support ゼロ as an alternative to ぜろ in this exercise. I'll do a quick look over the other exercises tomorrow to see if they might need updating as well.

Thanks for reporting.
