### ISSUE TITLE
Suggestions on how quiz answers are displayed

### ISSUE THREAD

**Issue by anitahuskies** [SethClydesdale/genki-study-resources#4]
After I finish a quiz, I get this message for the wrong answers: Keep studying! "The items underlined in red were answered wrong, the correct answers are listed underneath in red". 

Could you put the wrong answer in one color and the correct answer in *another* color?

On my phone sometimes there are 2 colors, but they are orange and red, which are very hard to differentiate.  I suggest red and blue, red and green...

BTW, I do not have any color blindness.

Love the program and it's helping me a lot with Genki! Thanks!
![Screen Shot 2019-08-23 at 3 39 39 PM](https://user-images.githubusercontent.com/54456824/63625934-72ae6280-c5be-11e9-9a5c-55f2597afdf7.png)

**Comment by SethClydesdale** [comment]
Hi @anitahuskies,

Thanks for your feedback, I'm glad to hear you've found this program helpful. I can see how it may be difficult to differentiate the correct answers from the wrong answers, especially on the multiple choice quizzes where the correct answer is shown in orange. As for the written quizzes, the problem isn't too glaring, but I think that could use an update as well to better highlight the correct and incorrect answers.

**For multiple choice:** incorrect-correct orange --> green or blue. I'm debating on this, because I think green may conflict with the current chosen answers which are green, so blue may be the better choice.

**For written quizzes:** I'll _possibly_ display the incorrect texts in red and correct in green (though I may keep it default color for readability; I'll have to perform tests) along with the pre-existing underline, but the correct answers underneath will definitely be changed to green as to better highlight that they're correct.

Thanks again, I'll let you know when I've made changes pertaining to your suggestion.

**Comment by SethClydesdale** [comment]
Hi again,

The colors for the correct answers to wrong answers should be updated now.
- **multiple choice**: orange --> blue
![](https://i25.servimg.com/u/f25/18/45/41/65/change10.png)

- **written quiz**: red --> green (inputted text color was retained to avoid conflicts with correctly answered questions)
![](https://i25.servimg.com/u/f25/18/45/41/65/change11.png)

Hope that helps make things easier. If anymore issues/suggestions, feel free to let me know. 👍 

Thanks again.

**Comment by anitahuskies** [comment]
Wow, ありがとうございます!

I'm studying for the N5 also. Will sign up for the Dec 1st test.
Have a great weekend!

Anita

**Comment by SethClydesdale** [comment]
どういたしまして。

Do your best on the exam!

Likewise, have a good one! 😉
