### ISSUE TITLE
Workbook

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#58]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-2/workbook-6/
Erroneous content
いいえ、(わたしは/)かいしゃいんじゃないです。
Correction of the content
いいえ、(わたしは/)かいしゃいんじゃないです
By putting an extra 。 in the answer you end up having 。。

Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-4/grammar-6/
Erroneous content
日曜日に買い物をしました。
Correction of the content
たけしさんは日曜日に町でメアリーさんと映画を見ました。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thanks, I've corrected the stray period in lesson 2's workbook. However, for "Practice: Past Tense 2" (grammar-6) in lesson 4, the correction seems to go against what's listed in the answer key?

> Link to the page that contains the mistake(s)
> https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-4/grammar-6/
> Erroneous content
> 日曜日に買い物をしました。
> Correction of the content
> たけしさんは日曜日に町でメアリーさんと映画を見ました。

![](https://i.imgur.com/RsF2nOT.png)

**Comment by AyaVK** [comment]
Sorry, must have looked in the wrong place...
I found far less mistakes in the workbook section than in the textbook section.
However the textbook section sticks to the Kanji's used in the book and the workbook section uses Kanji's a lot more liberally. It's not a bad thing but it looks like the textbook and workbook sections were entered by different persons.
I'm almost done with verifying the answers you have here and those on my pages:
http://www.ayaya.be/Japans/Oefeningen/index.html
I haven't studied past chapter 20 so I have no data on that.

Best regards,

理VK

**Comment by SethClydesdale** [comment]
Ah, no problem, I'll mark this closed then.

> I found far less mistakes in the workbook section than in the textbook section.

That may be because the workbook section received far more attention through various upgrades over the course of development, which I ended up catching quite a few errors and fixing haha.

> However the textbook section sticks to the Kanji's used in the book and the workbook section uses Kanji's a lot more liberally. It's not a bad thing but it looks like the textbook and workbook sections were entered by different persons.

In regards to the workbook using both kana and kanji input, I tried to include alternative answers in the event someone does not yet know a certain kanji, so if for example they type the kana instead of the kanji, the answer would still be correct. A common complaint was that answers would be marked wrong erroneously if you used a mix of kana AND kanji, but thankfully that was fixed a few months ago. While not every possibility is supported, I tried to include as much as possible.

The textbook or "practice problems" tend to stick with their kanji since it only requires reading, but should someone not know a certain kanji, they can still utilize the text selection and dictionary to look it up.

Thanks again for taking the time to look over everything.
