### ISSUE TITLE
"a watch I got from my girlfriend" translated into Japanese

### ISSUE THREAD

**Issue by kwakkles** [SethClydesdale/genki-study-resources#64]
Page 89, IV-A, question # 3 at 
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-15/grammar-5/

"a watch I got from my girlfriend" is asked to be translated into Japanese.

The answer options:

彼女がくれた時計
彼女があげた時計
彼女にもらった時計

All three answers mean "a watch I got from my girlfriend", so there is no wrong answer here, let alone two wrong answers. 
For this content, you don't have to necessarily change any of it. It's actually neat to know how to say it in three different ways. Upon your web site grading it at the end, though, don't mark any answer as wrong - just color them all in the light blue coloring which means correct.

**Comment by SethClydesdale** [comment]
Hello @kwakkles,

Ah, the reason it's like this is because that is the only answer noted in the answer key.

With あげる and くれる the subject of the sentence is the giver, however, with もらう the subject of the sentence is the recipient. So I'm assuming in this instance, もらう is most likely used, because the subject of the sentence (you) is supposed to identify more closely with the receiving end. That is, the watch, is a gift you received (or "got") from your girlfriend.

Each could roughly be translated to..
彼女がくれた時計 a watch _my girlfriend_ gave me.
彼女があげた時計 a watch _girlfriend_ gave.. her boyfriend? (It would be kinda weird to use あげる this way, since the speaker -- the girlfriend -- probably wouldn't refer to herself as such.. would most likely use 彼にあげた時計, but don't quote me on this)
彼女にもらった時計 a watch _I_ got from my girlfriend.

I think in terms of "{ITEM} I got/received from {GIVER}", もらう would be used. In contrast, if it's "{ITEM} {GIVER} gave me", くれる would be used instead.

**Comment by kwakkles** [comment]
The contrast between right and wrong for this answer selection is between the exact words of 'give' and 'receive' . It is cloaked in the less formal word 'got' that the Genki authors used in the question content. This small three-letter word 'got' majorly threw me off because it is broadly used in American English. 

Thanks for the thorough explanation you provided.

**Comment by SethClydesdale** [comment]
No problem. Indeed, it can be a bit confusing, and if I recall this also threw me off when I was first studying -- so much so, I had to go back and re-read the section on the giving verbs. Overall, the trick to figuring it out tends to lie more in _who_ the subject of the sentence is. If you can find that, it becomes much easier to determine if もらう or くれる should be used.
